### ISSUE TITLE
pnpm bootstrap is failing 

### ISSUE THREAD

**Issue by SigmaOutdoors** [apache/incubator-kie-tools#1145]
Looking for any insight on my error when attempting to 

**pnpm bootstrap**

seems to be failing on liblzma-config.sh command

```
<omitted success>
.../node_modules/lzma-native install: gyp info spawn /usr/bin/python3
.../node_modules/lzma-native install: gyp info spawn args [
.../node_modules/lzma-native install: gyp info spawn args   '/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
.../node_modules/lzma-native install: gyp info spawn args   'binding.gyp',
.../node_modules/lzma-native install: gyp info spawn args   '-f',
.../node_modules/lzma-native install: gyp info spawn args   'make',
.../node_modules/lzma-native install: gyp info spawn args   '-I',
.../node_modules/lzma-native install: gyp info spawn args   '/tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native/build/config.gypi',
.../node_modules/lzma-native install: gyp info spawn args   '-I',
.../node_modules/lzma-native install: gyp info spawn args   '/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
.../node_modules/lzma-native install: gyp info spawn args   '-I',
.../node_modules/lzma-native install: gyp info spawn args   '/root/.cache/node-gyp/16.14.0/include/node/common.gypi',
.../node_modules/lzma-native install: gyp info spawn args   '-Dlibrary=shared_library',
.../node_modules/lzma-native install: gyp info spawn args   '-Dvisibility=default',
.../node_modules/lzma-native install: gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.0',
.../node_modules/lzma-native install: gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp',
.../node_modules/lzma-native install: gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.0/<(target_arch)/node.lib',
.../node_modules/lzma-native install: gyp info spawn args   '-Dmodule_root_dir=/tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native',
.../node_modules/lzma-native install: gyp info spawn args   '-Dnode_engine=v8',
.../node_modules/lzma-native install: gyp info spawn args   '--depth=.',
.../node_modules/lzma-native install: gyp info spawn args   '--no-parallel',
.../node_modules/lzma-native install: gyp info spawn args   '--generator-output',
.../node_modules/lzma-native install: gyp info spawn args   'build',
.../node_modules/lzma-native install: gyp info spawn args   '-Goutput_dir=.'
.../node_modules/lzma-native install: gyp info spawn args ]
.../node_modules/lzma-native install: gyp: Call to 'sh liblzma-config.sh "/tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native/build" "/tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 2 while in binding.gyp. while trying to load binding.gyp
.../node_modules/lzma-native install: gyp ERR! configure error 
.../node_modules/lzma-native install: gyp ERR! stack Error: `gyp` failed with exit code: 1
.../node_modules/lzma-native install: gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/configure.js:259:16)
.../node_modules/lzma-native install: gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
.../node_modules/lzma-native install: gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
.../node_modules/lzma-native install: gyp ERR! System Linux 5.10.76-linuxkit
.../node_modules/lzma-native install: gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64/lzma_native.node" "--module_name=lzma_native" "--module_path=/tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93" "--python=/usr/bin/python3"
.../node_modules/lzma-native install: gyp ERR! cwd /tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native
.../node_modules/lzma-native install: gyp ERR! node -v v16.14.0
.../node_modules/lzma-native install: gyp ERR! node-gyp -v v8.4.1
.../node_modules/lzma-native install: gyp ERR! not ok 
.../node_modules/lzma-native install: node-pre-gyp ERR! build error 
.../node_modules/lzma-native install: node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64/lzma_native.node --module_name=lzma_native --module_path=/tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93 --python=/usr/bin/python3' (1)
.../node_modules/lzma-native install: node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/kie-tools-main/node_modules/.pnpm/node-pre-gyp@0.11.0/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
.../node_modules/lzma-native install: node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
.../node_modules/lzma-native install: node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
.../node_modules/lzma-native install: node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
.../node_modules/lzma-native install: node-pre-gyp ERR! System Linux 5.10.76-linuxkit
.../node_modules/lzma-native install: node-pre-gyp ERR! command "/usr/bin/node" "/tmp/kie-tools-main/node_modules/.pnpm/node-pre-gyp@0.11.0/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
.../node_modules/lzma-native install: node-pre-gyp ERR! cwd /tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native
.../node_modules/lzma-native install: node-pre-gyp ERR! node -v v16.14.0
.../node_modules/lzma-native install: node-pre-gyp ERR! node-pre-gyp -v v0.11.0
.../node_modules/lzma-native install: node-pre-gyp ERR! not ok 
.../node_modules/lzma-native install: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64/lzma_native.node --module_name=lzma_native --module_path=/tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93 --python=/usr/bin/python3' (1)
.../node_modules/lzma-native install: Failed
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by SigmaOutdoors** [comment]
After looking further up the chain, it looks like it goes into this because it can't find and a prebuilt lzma_native-v6.0.1-n-api-linux-arm64.tar.gz file.

.../node_modules/playwright install$ node install.js
.../node_modules/lzma-native install: node-pre-gyp info it worked if it ends with ok
.../node_modules/lzma-native install: node-pre-gyp info using node-pre-gyp@0.11.0
.../node_modules/lzma-native install: node-pre-gyp info using node@16.14.0 | linux | arm64
.../node_modules/lzma-native install: node-pre-gyp WARN Using request for node-pre-gyp https download 
.../node_modules/lzma-native install: node-pre-gyp info check checked for "/tmp/kie-tools-main/node_modules/.pnpm/lzma-native@6.0.1/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64/lzma_native.node" (not found)
.../node_modules/lzma-native install: node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-linux-arm64.tar.gz
.../node_modules/lzma-native install: node-pre-gyp http 404 https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-linux-arm64.tar.gz
.../node_modules/lzma-native install: node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-linux-arm64.tar.gz 
.../node_modules/lzma-native install: node-pre-gyp WARN Pre-built binaries not found for lzma-native@6.0.1 and node@16.14.0 (node-v93 ABI, glibc) (falling back to source compile with node-gyp) 
.../node_modules/lzma-native install: node-pre-gyp http 404 status code downloading tarball https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-linux-arm64.tar.gz 
.../node_modules/lzma-native install: gyp info it worked if it ends with ok

**Comment by SigmaOutdoors** [comment]
I found the problem, it won't work on ARM processors so I created a Docker image that runs AMD.  I was able to get though the bootstrap with success!  However trying this command fails (way into it), any help would be appreciated

```
pnpm -r -F kie-editors-standalone... build:dev

Progress (2): 4.7 kB | 21 kB   
│                             
│ Downloaded from public-snapshots-repo: https://oss.sonatype.org/content/repositories/public/org/codehaus/plexus/plexus-compiler-manager/2.8.4/plexus-compiler-manager-2.8.4.jar (4.7 kB at 9.0 kB/s)
│ Downloaded from public-snapshots-repo: https://oss.sonatype.org/content/repositories/public/org/codehaus/plexus/plexus-compiler-javac/2.8.4/plexus-compiler-javac-2.8.4.jar (21 kB at 39 kB/s)
│ [INFO] Changes detected - recompiling the module!
[INFO] Compiling 36 source files to /tmp/kie-tools-main/packages/stunner-editors/errai-reflections/reflections/target/classes
│ #
│ # A fatal error has been detected by the Java Runtime Environment:
│ #
│ #  SIGSEGV (0xb) at pc=0x0000004015beaca4, pid=2169, tid=2223
│ #
│ # JRE version: OpenJDK Runtime Environment (Red_Hat-11.0.16.0.8-1.el9_0) (11.0.16+8) (build 11.0.16+8-LTS)
│ # Java VM: OpenJDK 64-Bit Server VM (Red_Hat-11.0.16.0.8-1.el9_0) (11.0.16+8-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
│ # Problematic frame:
│ # J 10503 c1 java.util.HashMap.getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.16 (23 bytes) @ 0x0000004015beaca4 [0x0000004015beace0+0xffffffffffffffc4]
│ #
│ # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
│ #
│ # An error report file with more information is saved as:
│ # /tmp/kie-tools-main/packages/stunner-editors/hs_err_pid2169.log
│ Compiled method (c1)  259333 10503       2       java.util.HashMap::getOrDefault (23 bytes)
│  total in heap  [0x0000004015beab10,0x0000004015beaf68] = 1112
│  relocation     [0x0000004015beac88,0x0000004015beacc8] = 64
│  main code      [0x0000004015beace0,0x0000004015beae40] = 352
│  stub code      [0x0000004015beae40,0x0000004015beae90] = 80
│  metadata       [0x0000004015beae90,0x0000004015beaea0] = 16
│  scopes data    [0x0000004015beaea0,0x0000004015beaef0] = 80
│  scopes pcs     [0x0000004015beaef0,0x0000004015beaf50] = 96
│  dependencies   [0x0000004015beaf50,0x0000004015beaf58] = 8
│  nul chk table  [0x0000004015beaf58,0x0000004015beaf68] = 16
│ Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
│ #
│ # If you would like to submit a bug report, please visit:
│ #   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%209&component=java-11-openjdk
│ #
│ qemu: uncaught target signal 6 (Aborted) - core dumped
└─ Failed in 4m 24.7s
packages/kie-bc-editors build:dev$ rimraf dist && pnpm copy:css && tsc -p tsconfig.dev.json
│ > @kie-tools/kie-bc-editors@0.0.0 copy:css /tmp/kie-tools-main/packages/kie-bc-editors
│ > copyfiles -u 1 "src/**/*.{sass,scss,css}" dist/
└─ Done in 36.5s
/tmp/kie-tools-main/packages/stunner-editors:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @kie-tools/stunner-editors@0.0.0 build:dev: `run-script-os`


```

**Comment by tiagobento** [comment]
Hi @SigmaOutdoors!

Doesn't look like our build has ever run on an arm64 Linux before. I occasionally develop on my M1 MacBook Air, which would be arm64 macOS, but I've never had such failures. Glad to know you were able to setup an amd64 VM.

Regarding the Java issue,  I have no idea what could be happening. We use OpenJDK 11 on our CI and I've never seen this error before. If you have access to another amd64 environment and could try and reproduce, maybe this would be a good start to finding the root cause.

**Comment by SigmaOutdoors** [comment]
Thanks for responding. Like I said, I was able to build a Docker image to take the ARM out of the equation.  Then on the above java issue I thought maybe it was disk space, so I moved it to a place with more disk - it compiled for like an hour and dumped here (below)...maybe it is my Docker image causing issues, I will keep trying.


```
[INFO] Adding ignorable dependency: org.wildfly.security:wildfly-elytron:jar
│ [INFO]   Adding ignore: *
│ [INFO] 
│ [INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (no-duplicate-declared-dependencies) @ errai-data-binding ---
│ [INFO] 
│ [INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (ban-unwanted-deps) @ errai-data-binding ---
│ [INFO] 
│ [INFO] --- maven-checkstyle-plugin:3.0.0:check (validate) @ errai-data-binding ---
│ #
│ # A fatal error has been detected by the Java Runtime Environment:
│ #
│ #  SIGSEGV (0xb) at pc=0x00000040150b3760, pid=2130, tid=2184
│ #
│ # JRE version: OpenJDK Runtime Environment (Red_Hat-11.0.16.0.8-1.el9_0) (11.0.16+8) (build 11.0.16+8-LTS)
│ # Java VM: OpenJDK 64-Bit Server VM (Red_Hat-11.0.16.0.8-1.el9_0) (11.0.16+8-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
│ # Problematic frame:
│ # J 20655 c1 com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.logicalOrExpression()V (101 bytes) @ 0x00000040150b3760 [0x00000040150b3720+0x0000000000000040]
│ #
│ # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
│ #
│ # An error report file with more information is saved as:
│ # /etc/kie-tools-main/packages/stunner-editors/hs_err_pid2130.log
│ Compiled method (c1) 2579129 20656   !   3       com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer::conditionalExpression (1033 bytes)
│  total in heap  [0x000000401664d010,0x00000040166559a8] = 35224
│  relocation     [0x000000401664d188,0x000000401664d870] = 1768
│  main code      [0x000000401664d880,0x00000040166532c0] = 23104
│  stub code      [0x00000040166532c0,0x0000004016653650] = 912
│  oops           [0x0000004016653650,0x0000004016653678] = 40
│  metadata       [0x0000004016653678,0x0000004016653730] = 184
│  scopes data    [0x0000004016653730,0x00000040166544f0] = 3520
│  scopes pcs     [0x00000040166544f0,0x0000004016655580] = 4240
│  dependencies   [0x0000004016655580,0x00000040166555a0] = 32
│  handler table  [0x00000040166555a0,0x00000040166555d0] = 48
│  nul chk table  [0x00000040166555d0,0x00000040166559a8] = 984
│ Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
│ #
│ # If you would like to submit a bug report, please visit:
│ #   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%209&component=java-11-openjdk
│ #
│ qemu: uncaught target signal 6 (Aborted) - core dumped
└─ Failed in 43m 4.6s
/etc/kie-tools-main/packages/stunner-editors:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @kie-tools/stunner-editors@0.0.0 build:dev: `run-script-os`
Exit status 134

```

**Comment by tiagobento** [comment]
This package requires a reasonable amount of RAM to be built. Can you try configuring Maven with `export MAVEN_OPTS=-Xmx2g`?

**Comment by SigmaOutdoors** [comment]
I will do that - thank you!

**Comment by tiagobento** [comment]
@SigmaOutdoors Any luck?

**Comment by SigmaOutdoors** [comment]
Not on my Mac, but I was able to create a Docker Image on a linux box and now I am having this issue (link below to KIE forums) building the stunner editors.  Thank you for checking back in, I appreciate it.

https://kie.zulipchat.com/#narrow/stream/232678-jbpm/topic/Failed.20Build.20Collection.20of.20Deps.20on.20Stunner.20Editors.20-.20Lib

**Comment by tiagobento** [comment]
@SigmaOutdoors Following the discussion on Zulip, closing this issue.
