### ISSUE TITLE
Unable to build project locally

### ISSUE THREAD

**Issue by hikemachado** [apache/incubator-kie-tools#1423]
I'm trying to build from source tag 0.26.0

pnpm bootstrap

but I got the followin error:

```
[bootstrap] Linking packages with self...
[link-packages-with-self] Linking 'kie-tools-root'. node_modules\kie-tools-root -> ..
node:fs:1700
  handleErrorFromBinding(ctx);
  ^

Error: EPERM: operation not permitted, symlink '..' -> 'node_modules\kie-tools-root'
    at Object.symlinkSync (node:fs:1700:3)
    at selfLink (D:\henri\dev\kie-tools\scripts\bootstrap\link_packages_with_self.js:53:6)
    at D:\henri\dev\kie-tools\scripts\bootstrap\link_packages_with_self.js:36:5
    at Array.forEach (<anonymous>)
    at main (D:\henri\dev\kie-tools\scripts\bootstrap\link_packages_with_self.js:22:38) {
  errno: -4048,
  syscall: 'symlink',
  code: 'EPERM',
  path: '..',
  dest: 'node_modules\\kie-tools-root'
}
node:child_process:935
    throw err;
    ^

Error: Command failed: node D:\henri\dev\kie-tools\scripts\bootstrap\link_packages_with_self.js
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Object.<anonymous> (D:\henri\dev\kie-tools\scripts\bootstrap\bootstrap.js:39:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 26032,
  stdout: null,
  stderr: null
}
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

npm version 16.19.0
go : 1.19.5
pnpm: 7.0.0
java 11
maven 3.8.7 
windows 11 pro

Att,
Henrique

**Comment by tiagobento** [comment]
Hi @hikemachado! I think this might be a permission issue. Can you please double-check if you have the correct write permission on this FS? Also, maybe try running this as Admin just to see what happens..

**Comment by hikemachado** [comment]
HI @tiagobento ,
It was a permission issue, I just executed as admin and it worked

Thanks a lot
