### ISSUE TITLE
Can not run the DMN after "Include Model"

### ISSUE THREAD

**Issue by phungvannarich-kepler-aavn** [apache/incubator-kie-tools#2757]
I always get error with "Run" function whenever "Include Model"

Before "Include Model":
![before](https://github.com/user-attachments/assets/5b9587c3-9a67-4d5c-b9d5-451db1b03a42)

After "Include Model":
![after](https://github.com/user-attachments/assets/ee06e561-35a2-42f6-9a21-1c5dce19d89f)

This is the included DMN:
![included rule](https://github.com/user-attachments/assets/fe14e750-7eb4-43e3-b69d-9496893dad96)

This is the error I saw on browser:
![error browser](https://github.com/user-attachments/assets/0c75a6c9-d57a-4f64-9e94-2b99857aecce)

This is the error from extended service:
`2024-11-21 10:43:43,639 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-41) HTTP Request to /jitdmn/dmnresult failed, error id: f60c9b73-5a0f-405c-bbf3-828da9113c53-80: org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: DMN Model with name=Untitled and namespace=https://kiegroup.org/dmn/_FD03680C-463E-460E-B7FB-A3DD7CB2E05C failed to import a DMN with namespace=http://www.drools.org/kie/dmn/1.1 name=test locationURI=RuleDemo.dmn, modelName=null. 
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:107)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:344)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:205)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:452)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: DMN Model with name=Untitled and namespace=https://kiegroup.org/dmn/_FD03680C-463E-460E-B7FB-A3DD7CB2E05C failed to import a DMN with namespace=http://www.drools.org/kie/dmn/1.1 name=test locationURI=RuleDemo.dmn, modelName=null. 
	at org.kie.dmn.feel.util.Either.getOrElseThrow(Either.java:66)
	at org.kie.dmn.core.assembler.DMNAssemblerService.enrichDMNResourcesWithImportsDependencies(DMNAssemblerService.java:139)
	at org.kie.dmn.core.internal.utils.DMNRuntimeBuilder$DMNRuntimeBuilderConfigured.fromResources(DMNRuntimeBuilder.java:188)
	at org.kie.kogito.jitexecutor.dmn.DMNEvaluator.fromMultiple(DMNEvaluator.java:92)
	at org.kie.kogito.jitexecutor.dmn.JITDMNServiceImpl.evaluateModel(JITDMNServiceImpl.java:151)
	at org.kie.kogito.jitexecutor.dmn.JITDMNServiceImpl_ClientProxy.evaluateModel(Unknown Source)
	at org.kie.kogito.jitexecutor.dmn.api.JITDMNResource.jitdmnResult(JITDMNResource.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	... 15 more`

I’m unsure how to investigate this issue. Could you please assist me in resolving it?

**Comment by yesamer** [comment]
Hi @phungvannarich-kepler-aavn, which version of KIE Sandbox are you using, please?

**Comment by phungvannarich-kepler-aavn** [comment]
@yesamer, Here is the version information; I hope it helps:
Build Version: 0.32.0
Kogito Runtimes Version: 1.40.0.Final
Quarkus Version: 2.16.7.Final
DMN Dev deployments image URL: quay.io/kie-tools/dmn-dev-deployment-base-image:0.32.0
Extended Services version: 0.32.0
Commit SHA: 0b28a10ae3

![image](https://github.com/user-attachments/assets/cf744b00-8c88-40e9-bd0f-04faafc7692e)

**Comment by yesamer** [comment]
@phungvannarich-kepler-aavn can you please try to reproduce it here ---> https://sandbox.kie.org/dev/#/ ?

**Comment by phungvannarich-kepler-aavn** [comment]
@yesamer, I tested it, and it works on your URL.

However, when I compare it with my KIE Sandbox, I notice a difference in the request.

My KIE Sandbox:
![image](https://github.com/user-attachments/assets/8b8ac2c9-4315-4e3f-a4e8-9f71692bb1d5)

Your KIE Sandbox:
![image](https://github.com/user-attachments/assets/7ebd895e-7f30-4591-b856-10c0f0a464c5)

Could this difference be the cause of the issue?

**Comment by yesamer** [comment]
@phungvannarich-kepler-aavn The point is, the 0.32.0 is very old, it was released more than one year ago. The dev version I shared with you is based on our 09/24`main` version. 
The Next release (10.0.0) will contain the change, you just need to wait it...

**Comment by phungvannarich-kepler-aavn** [comment]
@yesamer  Thank you so much!

Do you have an estimated release date for version 10.0.0?

**Comment by yesamer** [comment]
@phungvannarich-kepler-aavn Unfortunately not yet, but hopefully EOY we should release 10.0.0.
